# Школа машинного обучения

<a href="https://mipt.ru/science/labs/laboratoriya-neyronnykh-sistem-i-glubokogo-obucheniya/"><img align="right" src="https://avatars1.githubusercontent.com/u/29918795?v=4&s=200" alt="DeepHackLab" style="position:relative;top:-40px;right:10px;height:100px;" /></a>



### Физтех-Школа Прикладной математики и информатики МФТИ 
### Лаборатория нейронных сетей и глубокого обучения (DeepHackLab)  


## Домашнее задание 1
### Основы Python и пакет NumPy
---


In [3]:
import numpy as np
import random
import scipy.stats as sps

### Задача 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [25]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j), здесь i -- число строк,
# j -- число столбцов.
a = np.random.sample((20,20))
b = np.random.sample((20,20))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
print(a.ndim, b.ndim)
print(a)
print(b)

2 2
[[0.79934662 0.76525355 0.10651511 0.10459661 0.88377654 0.85586013
  0.35002246 0.09435959 0.5537966  0.8984887  0.73769721 0.59328451
  0.2910472  0.67958125 0.3362317  0.30123932 0.27916714 0.89203045
  0.83054259 0.85830609]
 [0.68209738 0.42183611 0.51844463 0.10606239 0.10661698 0.86950015
  0.04036174 0.52134404 0.98471059 0.31762152 0.75494981 0.44283259
  0.47660796 0.5844622  0.94188163 0.02462432 0.11127627 0.86264146
  0.49439562 0.5843944 ]
 [0.46732025 0.47912368 0.3467934  0.95118005 0.80902901 0.32558518
  0.69721939 0.12511657 0.55849382 0.44106976 0.56528428 0.44448879
  0.42090495 0.24561727 0.6318628  0.25822796 0.44002824 0.96996293
  0.97373901 0.18969232]
 [0.59368423 0.80672    0.02719118 0.60968199 0.01746137 0.00746888
  0.11553814 0.493031   0.14087252 0.00572468 0.05870671 0.3981745
  0.51934889 0.87206572 0.02725226 0.2751915  0.19086736 0.92850409
  0.73856645 0.82928955]
 [0.99734496 0.06957153 0.4576396  0.58916286 0.34850914 0.61067453
  0.64240336 

In [26]:
def mult_vectors(a, b):
    summa = 0
    for i in range(len(a)):
        summa += a[i]*b[i]
    return summa
def mult(a, b):
    if a.shape[0] != b.shape[1]:
        print ("Matrixes can`t be multiplied")
        return
    c = np.zeros((a.shape[0], b.shape[1]))
    for row in range(a.shape[0]):
        for column in range(b.shape[1]):
            c[row][column]  = mult_vectors(a[row] ,b[:, column])
    return c


[[6.03784392 4.76057338 5.50976535 4.94530485 4.9006172  6.18370486
  4.97673795 6.47282867 3.49777779 3.58760007 6.45433079 6.03899399
  6.36171141 6.13517399 5.51682002 5.27167271 6.48276233 5.98714857
  5.95382543 5.65151585]
 [5.60758167 3.99180462 3.89179486 4.27980772 4.75501925 5.18066192
  3.87070032 5.58543222 3.58857302 3.77334656 5.55460686 4.55836996
  5.87846372 5.6689581  5.09600676 4.45833477 6.07955653 5.18379912
  5.37912529 4.6660655 ]
 [5.59627892 4.88433037 5.04238353 5.36228842 4.34344345 5.97775451
  4.2899139  6.55758574 4.13401774 3.59345202 6.64031267 5.42004943
  5.80504465 5.58140512 4.78077834 4.82938601 6.29139171 5.92163192
  5.44877762 4.8846989 ]
 [3.78105846 3.09458418 2.95700562 4.18894514 2.66123304 4.1892251
  3.62138985 3.74901552 2.90517765 2.55574072 3.86640104 3.86530853
  4.79588055 3.73559469 3.1343308  3.2416171  4.25040266 2.91769476
  3.92043624 4.13007201]
 [5.67636485 4.84286198 4.43064089 5.49036033 4.47020281 5.63739014
  4.56282957 5.84

In [27]:
def np_mult(a, b):
    return a@b
print(np_mult(a, b))

[[6.03784392 4.76057338 5.50976535 4.94530485 4.9006172  6.18370486
  4.97673795 6.47282867 3.49777779 3.58760007 6.45433079 6.03899399
  6.36171141 6.13517399 5.51682002 5.27167271 6.48276233 5.98714857
  5.95382543 5.65151585]
 [5.60758167 3.99180462 3.89179486 4.27980772 4.75501925 5.18066192
  3.87070032 5.58543222 3.58857302 3.77334656 5.55460686 4.55836996
  5.87846372 5.6689581  5.09600676 4.45833477 6.07955653 5.18379912
  5.37912529 4.6660655 ]
 [5.59627892 4.88433037 5.04238353 5.36228842 4.34344345 5.97775451
  4.2899139  6.55758574 4.13401774 3.59345202 6.64031267 5.42004943
  5.80504465 5.58140512 4.78077834 4.82938601 6.29139171 5.92163192
  5.44877762 4.8846989 ]
 [3.78105846 3.09458418 2.95700562 4.18894514 2.66123304 4.1892251
  3.62138985 3.74901552 2.90517765 2.55574072 3.86640104 3.86530853
  4.79588055 3.73559469 3.1343308  3.2416171  4.25040266 2.91769476
  3.92043624 4.13007201]
 [5.67636485 4.84286198 4.43064089 5.49036033 4.47020281 5.63739014
  4.56282957 5.84

In [28]:
%%time
# засечем время работы функции без NumPy
mult(a,b)

Wall time: 7.02 ms


array([[6.03784392, 4.76057338, 5.50976535, 4.94530485, 4.9006172 ,
        6.18370486, 4.97673795, 6.47282867, 3.49777779, 3.58760007,
        6.45433079, 6.03899399, 6.36171141, 6.13517399, 5.51682002,
        5.27167271, 6.48276233, 5.98714857, 5.95382543, 5.65151585],
       [5.60758167, 3.99180462, 3.89179486, 4.27980772, 4.75501925,
        5.18066192, 3.87070032, 5.58543222, 3.58857302, 3.77334656,
        5.55460686, 4.55836996, 5.87846372, 5.6689581 , 5.09600676,
        4.45833477, 6.07955653, 5.18379912, 5.37912529, 4.6660655 ],
       [5.59627892, 4.88433037, 5.04238353, 5.36228842, 4.34344345,
        5.97775451, 4.2899139 , 6.55758574, 4.13401774, 3.59345202,
        6.64031267, 5.42004943, 5.80504465, 5.58140512, 4.78077834,
        4.82938601, 6.29139171, 5.92163192, 5.44877762, 4.8846989 ],
       [3.78105846, 3.09458418, 2.95700562, 4.18894514, 2.66123304,
        4.1892251 , 3.62138985, 3.74901552, 2.90517765, 2.55574072,
        3.86640104, 3.86530853, 4.79588055, 3

In [29]:
%%time
# засечем время работы функции с NumPy
np_mult(a,b)

Wall time: 0 ns


array([[6.03784392, 4.76057338, 5.50976535, 4.94530485, 4.9006172 ,
        6.18370486, 4.97673795, 6.47282867, 3.49777779, 3.58760007,
        6.45433079, 6.03899399, 6.36171141, 6.13517399, 5.51682002,
        5.27167271, 6.48276233, 5.98714857, 5.95382543, 5.65151585],
       [5.60758167, 3.99180462, 3.89179486, 4.27980772, 4.75501925,
        5.18066192, 3.87070032, 5.58543222, 3.58857302, 3.77334656,
        5.55460686, 4.55836996, 5.87846372, 5.6689581 , 5.09600676,
        4.45833477, 6.07955653, 5.18379912, 5.37912529, 4.6660655 ],
       [5.59627892, 4.88433037, 5.04238353, 5.36228842, 4.34344345,
        5.97775451, 4.2899139 , 6.55758574, 4.13401774, 3.59345202,
        6.64031267, 5.42004943, 5.80504465, 5.58140512, 4.78077834,
        4.82938601, 6.29139171, 5.92163192, 5.44877762, 4.8846989 ],
       [3.78105846, 3.09458418, 2.95700562, 4.18894514, 2.66123304,
        4.1892251 , 3.62138985, 3.74901552, 2.90517765, 2.55574072,
        3.86640104, 3.86530853, 4.79588055, 3

### Задача 2
Напишите функцию, которая по данной последовательности $\{A_i\}_{i=1}^n$ строит последовательность $S_n$, где $S_k = \frac{A_1 + ... + A_k}{k}$.  
Аналогично -- с помощью библиотеки **NumPy** и без нее. Сравните скорость, объясните результат.

In [68]:
# функция, решающая задачу с помощью NumPy
def sec_av(A):
    B =  [1/(i+1) for i in range(len(A))]
    A = A.cumsum()[::]
    return A*B


In [76]:

# функция без NumPy
def stupid_sec_av(A):
    S = [0 for i in range(len(A))]
    S[0] = A[0]
    for i in range(1, len(A)):
        S[i] = (i*S[i-1] + A[i])/(i+1)
    return S

#a = np.array([1, 2, 3, 4])
#print(stupid_sec_av(a))

# зададим некоторую последовательность и проверим ее на ваших функциях. 
# Первая функция должна работать ~ в 50 раз быстрее
A = sps.uniform.rvs(size=10 **3) 

%time S1 = sec_av(A)
%time S2 = stupid_sec_av(A)
#проверим корректность:
print(np.abs(S1 - S2).sum())


Wall time: 498 µs
Wall time: 2 ms
2.0106138975961585e-13


### Задача 3

Пусть задан некоторый массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все четные элементы исходного массива нужно возвести в куб и записать в обратном порядке относительно позиций этих элементов. Массив $X$ при этом должен остаться без изменений. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке. 

In [175]:
# функция, решающая задачу с помощью NumPy
def transformation(X, a=1):
    Y = X.copy()
    Y[::2] = (Y[::2]**3) [::-1]
    Y[1::2] = a 
    Z = np.hstack((X, Y))
    Z = Z[::-1]
    return Y
a = np.array([1, 2, 3, 4, 5, 6])
print(transformation(a))

[125   1  27   1   1   1]


In [176]:
# функция, решающая задачу  без NumPy
def stupid_transformation(X, a= 1):
    Y = X.copy()
    for i in range(len(Y)):
        if i%2 == 0:
            Y[i]**= 3
        else:
            Y[i] = a
    for i in range (0, len(Y)//2, 2):
        Y[i], Y[len(Y) - i -2  + len(Y)%2] = Y[len(Y) - i -2+ len(Y)%2], Y[i]           
    Z = np.hstack((X, Y))
    Z = Z[::-1]    
    return Y
a = np.array([1, 2, 3, 4,5, 6])
print(stupid_transformation(a))


[125   1  27   1   1   1]


In [177]:
X = sps.uniform.rvs(size=10 ** 7) 
# здесь код эффективнее примерно в 20 раз. 
# если Вы вдруг соберетесь печатать массив без np -- лучше сначала посмотрите на его размер
%time S1 = transformation(X)
%time S2 = stupid_transformation(X)
# проверим корректность:
print(np.abs(S1 - S2).sum())

Wall time: 721 ms
Wall time: 9.17 s
0.0


Почему методы ***numpy*** оказываются эффективнее?

In [ ]:
# Ваш ответ

## Дополнительные задачи

Дополнительные задачи подразумевают, что Вы самостоятельно разберётесь в некоторых функциях ***numpy***, чтобы их сделать.  

Эти задачи не являются обязательными, но могут повлиять на Ваш рейтинг в лучшую сторону (точные правила учёта доп. задач будут оглашены позже).

### Задача 4*

Дана функция двух переменных: $f(x, y) = sin(x)cos(y)$ (это просто такой красивый 3D-график), а также дана функция для отрисовки $f(x, y)$ (`draw_f()`), которая принимает на вход двумерную сетку, на которой будет вычисляться функция.  

Вам нужно разобраться в том, как строить такие сетки (подсказка - это одна конкретная функция ***numpy***), и подать такую сетку на вход функции отрисовки.

In [ ]:
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline

def f(x, y):
    '''Функция двух переменных'''
    return np.sin(x) * np.cos(y)

def draw_f(grid_x, grid_y):
    '''Функция отрисовки функции f(x, y)'''
    fig = plt.figure(figsize=(10, 8))
    ax = Axes3D(fig)
    ax.plot_surface(grid_x, grid_y, f(grid_x, grid_y), cmap='inferno')
    plt.show()

In [ ]:
grid_x, grid_y = # Ваш код здесь

draw_f(gridx, gridy)

### Задача 5*

Вам дана картинка. При загрузке её размерность равна 3: **(w, h, num_channels)**, где **w** - ширина картинки в пикселях, **h** - высота картинки в пикселях, **num_channels** - количество каналов *(R, G, B, alpha)*.

Вам нужно "развернуть" картинку в одномерный массив размера w \* h \* num_channels, написав **одну строку кода**.

In [ ]:
from matplotlib import pyplot as plt
%matplotlib inline

In [ ]:
path_to_image = './image.png'
image_array = plt.imread(path_to_image)
plt.imshow(image_array);

In [ ]:
flat_image_array = # Ваш код здесь

In [ ]:
# здесь выведите размер нового массива